apiVersion: v1
clusters:
- name: "bloc-3-indiv"
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJXekNDQVFHZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQVZNUk13RVFZRFZRUURFd3ByZFdKbGNtNWwKZEdWek1CNFhEVEkyTURJeE9URXdORFl5TjFvWERUTTJNREl4T1RFd05EWXlOMW93RlRFVE1CRUdBMVVFQXhNSwphM1ZpWlhKdVpYUmxjekJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCS3BCaGlmN1h2TXF2WU5wCm1QSkkxSEx3L0RETUpBOEFyQzBNZE9BblB0M2MvVXgyck5FRnNYUFVJRE0zbGlNazJtZlZITkJreGdYaXRBckgKa1F4eGladWpRakJBTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZApEZ1FXQkJUYmtXcWwxdUJ1d2tQSGNYcm9ZV3RFeFNBbnd6QUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUFpK2FnCll6czdodldqOThTMHRaelpWZm1tQzN0SUtGdVhSY2FSdXZQRGw2TUNJQXM2K25SSEhTZGxYVjRicE9BRFA0NnoKK1dsaU5MQndsSklPbFB4MDdWWUgKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://07c6a1c1-476b-4d82-8202-0650ebe1cb02.api.k8s.fr-par.scw.cloud:6443
contexts:
- name: admin@bloc-3-indiv
  context:
    cluster: "bloc-3-indiv"
    user: bloc-3-indiv-admin
current-context: admin@bloc-3-indiv
kind: Config
preferences: {}
users:
- name: bloc-3-indiv-admin
  user:
    token: 0b8e21ff-6e43-4f05-bf5d-81e1b2d677b9