apiVersion: v1
kind: Service
metadata:
    name: argocd-server-proxy
    namespace: collector
spec:
    type: ExternalName
    externalName: argocd-server.deploy.svc.cluster.local
    ports:
        - name: http
          port: 80
          targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: argocd-server-ingress
    namespace: collector
    annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
    tls:
        - hosts:
              - argo.celianhamon.fr
          secretName: argocd-tls
    rules:
        - host: argo.celianhamon.fr
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: argocd-server-proxy
                            port:
                                number: 80
